baseURL = "https://hoad.kafe.one/"
languageCode = "en-us"
title = "hoa.d"
theme = "hyde-hyde"
disqusShortname = "hoa-d"
googleAnalytics = "G-YLG1KEYLCC"

[params]
    description = "a simple man who loves reading his mind \"on-the-fly\"."
    postNavigation = false
    toc = "tocbot"
    copyright = "hoad.kafe.one"
    custom_css = ["css/custom.css"]

[params.social]
    github = "hoadh"
    linkedin = "hoad"
    facebook = "hoadng"
    telegram = "hoadang"

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 1